---
# Variable Description
# monitor_user: is the username which is used by datadog to monitor mongodb related metrics
# monitor_password: password for monitor_user

- hosts: localhost
  connection: local
  vars:
    tvlk_mongod_initialization: true
  roles:
    - role: configure datadog
      datadog_checks:
        mongo:
          init_config:
          instances:
            - server: "mongodb://{{ monitor_user }}:{{ monitor_password }}@localhost:27017"
