---
# Variable Description
# monitor_user: is the username which is used by datadog to monitor mongodb related metrics
# monitor_password: password for monitor_user

- hosts: localhost
  connection: local
  vars:
    tvlk_mongod_initialization: true
  roles:
    - role: datadog-mongo-checks
      check_config:
        init_config:
          min_collection_interval: 20
        instances:
          server: "mongodb://{{ monitor_user }}:{{ monitor_password }}@localhost:27017"
