---
# required variables:
# service_name: name of the service
# replica_set_name: name of the replica set / mongodb cluster, if you are migrating from multi account you need to use the same replica_set_name
# mongodb_repl_oplog_size: <size of the mongo oplog in MB>
# pd_name: your product domain name
# hostname: FQDN of mongodb instances
# temporary_master_password: temporary master password for initial root user
# keyfile: keyfile for mongodb cluster, to generate key file you can run this command: openssl rand -base64 741
# datadog_api_key: you need to change the path of parameter store where you store the datadog api key
- hosts: localhost
  connection: local
  vars:
    tvlk_mongod_initialization: true
    keyfile: "{{ lookup('file','/tmp/keyfile')}}"
    datadog_api_key: "{{ lookup('aws_ssm','/tvlk-secret/shared/<changethiswithyourpd>/datadog.api.key',region='ap-southeast-1',decrypt=True)}}"
  pre_tasks:
    - block:
        - name: set instance hostname
          hostname:
            name: "{{ hostname }}"
      become: yes
      become_method: sudo
      when: keyfile and temporary_master_password != ""
  roles:
    - role: xfsvolume
      xfs_volume_mount: /var/lib/mongodb
    - role: mongod-3.6
      mongodb_authorization_enabled: false
      when: tvlk_mongod_initialization == true
    - role: datadog-agent
      datadog_api_key: "{{ datadog_api_key }}"
    - role: awslogs-config
      awslogs_app_name: "{{service_name}}-mongod"
      awslogs_app_log_settings:
        - file: "/var/log/mongodb/mongod.log"
          datetime_format: "%Y-%m-%dT%H:%M:%S.%f%z"
          group_name: "/tvlk/mongod/{{ service_name }}/mongod.log"
          time_zone: "UTC"
    - role: mongo-root-user
      login_password: "{{ temporary_master_password }}"
    - role: mongod-3.6
      mongodb_repl_set_name: "{{ replica_set_name }}"
      mongodb_keyfile_content: "{{ keyfile }}"
      when: tvlk_mongod_initialization == true
